INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (true, '3,502.10', e'Pariatur exercitation cillum nisi nulla consectetur. Laboris ipsum deserunt occaecat dolore. Aliquip non nostrud excepteur qui commodo non aliqua aliquip. Exercitation irure est voluptate occaecat.
', 'https://via.placeholder.com/150', 'Plasmox', '{aliqua,id,cupidatat,ex,tempor,id,consectetur}', '2023-02-12 10:18:42.343921', '2023-02-12 10:18:42.343921');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (false, '1,931.10', e'Aute sit aliqua Lorem excepteur. Cillum cupidatat duis dolore ut irure officia amet laborum consectetur occaecat. Tempor quis consectetur aliquip do. Veniam in magna dolore laboris in cillum nulla esse Lorem. Est Lorem magna fugiat veniam nostrud ipsum mollit est aliquip consectetur excepteur magna nulla irure.
', 'https://via.placeholder.com/150', 'Xumonk', '{anim,eiusmod,ad,eiusmod,ex,consequat,sunt}', '2023-02-12 10:18:42.347751', '2023-02-12 10:18:42.347751');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (false, '2,401.37', e'Tempor quis pariatur dolore deserunt esse esse aute. Sunt in do id qui voluptate aute minim anim deserunt. Voluptate dolor commodo et labore sit ea officia ullamco tempor. Officia Lorem eiusmod pariatur id voluptate qui culpa ipsum quis ullamco labore id. Culpa nisi nisi mollit esse commodo ex cillum id. Mollit et irure officia veniam tempor.
', 'https://via.placeholder.com/150', 'Atomica', '{irure,ex,consequat,et,adipisicing,duis,id}', '2023-02-12 10:18:42.351149', '2023-02-12 10:18:42.351149');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (false, '2,792.67', e'Commodo quis magna sit cupidatat ex eiusmod velit minim ut pariatur aliquip duis minim. Nostrud sunt esse fugiat eu culpa nostrud mollit esse pariatur adipisicing. Commodo qui dolor Lorem voluptate adipisicing irure ipsum exercitation magna ullamco enim aute magna. Commodo nisi dolore incididunt qui eiusmod do deserunt cillum. Eu aute adipisicing pariatur consectetur eu adipisicing et sit eu nostrud cillum.
', 'https://via.placeholder.com/150', 'Kiosk', '{id,do,non,esse,laborum,amet,laborum}', '2023-02-12 10:18:42.354763', '2023-02-12 10:18:42.354763');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (false, '3,283.74', e'Non adipisicing ipsum do consequat irure commodo cupidatat cupidatat occaecat id. Occaecat nostrud esse eu culpa. Proident ea nisi culpa cillum cupidatat.
', 'https://via.placeholder.com/150', 'Isoternia', '{sint,sunt,dolor,nulla,proident,pariatur,eu}', '2023-02-12 10:18:42.358560', '2023-02-12 10:18:42.358560');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (true, '1,292.57', e'Nulla pariatur in occaecat occaecat non nostrud reprehenderit minim. Quis ex laboris fugiat officia proident tempor aute sint elit aliquip nulla irure. Ullamco dolore elit qui laborum veniam excepteur Lorem culpa commodo sunt est.
', 'https://via.placeholder.com/150', 'Austech', '{dolor,elit,sunt,adipisicing,cupidatat,nulla,aliquip}', '2023-02-12 10:18:42.361818', '2023-02-12 10:18:42.361818');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (true, '2,834.14', e'Do mollit ullamco amet exercitation et labore sit exercitation sunt ut pariatur dolore proident. Irure consequat officia in eiusmod dolor dolore occaecat. Irure anim proident incididunt aliquip commodo. Dolore aute quis dolore eiusmod reprehenderit. Aliqua ad voluptate labore eiusmod laboris nostrud ipsum sint duis. Adipisicing ipsum consequat occaecat elit enim ullamco exercitation.
', 'https://via.placeholder.com/150', 'Voipa', '{commodo,ipsum,in,eu,velit,commodo,culpa}', '2023-02-12 10:18:42.364703', '2023-02-12 10:18:42.364703');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (false, '3,609.27', e'Officia magna ea aliqua elit incididunt culpa. Non labore ipsum nisi irure minim officia commodo magna occaecat in aliqua. Dolor ex magna exercitation aliquip velit voluptate culpa minim esse occaecat duis. Et aute ipsum ea ea velit. Cillum deserunt est consequat ullamco non commodo in reprehenderit anim.
', 'https://via.placeholder.com/150', 'Comtent', '{nisi,culpa,reprehenderit,sunt,aute,in,sunt}', '2023-02-12 10:18:42.367579', '2023-02-12 10:18:42.367579');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (false, '2,981.05', e'Ea officia esse mollit laboris. Ullamco eu do deserunt tempor culpa consequat. Ex sint est ea Lorem excepteur elit laborum do duis in. Nisi fugiat non dolore culpa incididunt sint ea eiusmod tempor nostrud ea.
', 'https://via.placeholder.com/150', 'Orbalix', '{magna,dolor,mollit,velit,ipsum,ut,cupidatat}', '2023-02-12 10:18:42.370798', '2023-02-12 10:18:42.370798');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (false, '1,092.01', e'Aliquip amet deserunt ipsum ad aliqua exercitation officia. Ex sit labore commodo cupidatat id laborum qui sint laborum dolor reprehenderit deserunt cupidatat minim. Tempor est nulla mollit duis sint veniam commodo adipisicing sint nisi. Dolore culpa irure aliqua occaecat enim occaecat nostrud sit nostrud esse est.
', 'https://via.placeholder.com/150', 'Balooba', '{irure,reprehenderit,ipsum,laborum,officia,eiusmod,ex}', '2023-02-12 10:18:42.373994', '2023-02-12 10:18:42.373994');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (false, '2,284.30', e'Nostrud velit in veniam voluptate ex aute. Aliquip ullamco laborum voluptate sint consectetur proident voluptate adipisicing. Aute non qui dolore consequat eu voluptate ad consequat pariatur irure ex commodo ea id. Ad in enim laboris enim sit sit consequat et. Ad consequat non aute in sunt.
', 'https://via.placeholder.com/150', 'Zensor', '{sint,nostrud,reprehenderit,magna,nisi,duis,occaecat}', '2023-02-12 10:18:42.377129', '2023-02-12 10:18:42.377129');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (false, '3,735.56', e'Culpa cillum minim ex sint labore est voluptate mollit aute ullamco. Esse commodo Lorem ex proident cupidatat pariatur excepteur sit. Nulla incididunt laboris duis ea laborum laboris do dolor incididunt proident consequat cupidatat fugiat. Et sit duis elit velit exercitation in qui ullamco magna nulla. Voluptate laboris anim nisi officia. Labore officia tempor mollit ea amet mollit sint velit id.
', 'https://via.placeholder.com/150', 'Exospeed', '{ullamco,quis,eu,veniam,pariatur,dolore,laboris}', '2023-02-12 10:18:42.380263', '2023-02-12 10:18:42.380263');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (false, '1,953.17', e'Ea exercitation eiusmod duis enim dolor esse cupidatat culpa. Esse amet magna in elit magna et. Deserunt laboris anim non in voluptate excepteur laborum non est aliqua.
', 'https://via.placeholder.com/150', 'Accupharm', '{ipsum,excepteur,veniam,officia,nulla,qui,incididunt}', '2023-02-12 10:18:42.383789', '2023-02-12 10:18:42.383789');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (true, '1,472.24', e'Nostrud officia reprehenderit est ad cupidatat cupidatat dolor pariatur est dolore excepteur. Veniam do excepteur consectetur in ea. Qui minim et nisi aute fugiat ea nostrud esse ullamco deserunt voluptate. Proident elit consectetur commodo tempor fugiat reprehenderit minim Lorem id et.
', 'https://via.placeholder.com/150', 'Wazzu', '{aute,occaecat,quis,duis,aliqua,excepteur,deserunt}', '2023-02-12 10:18:42.395810', '2023-02-12 10:18:42.395810');
INSERT INTO public.sasol_api_product ( active, price, description, picture, name, tags, created_at, updated_at) VALUES (true, '3,333.17', e'Adipisicing ad tempor in culpa officia velit ex anim nulla veniam nulla eu. Nulla irure sint proident pariatur elit. Exercitation sint aliquip in pariatur duis excepteur cupidatat ad ipsum do labore culpa et ad. Ex ipsum ex Lorem commodo et magna cupidatat est est dolor fugiat cupidatat do et.
', 'https://via.placeholder.com/150', 'Neocent', '{ullamco,voluptate,ipsum,reprehenderit,est,magna,dolore}', '2023-02-12 10:18:42.399818', '2023-02-12 10:18:42.399818');
