# Generated by Django 4.1.6 on 2023-02-12 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("index", models.IntegerField(primary_key=True, serialize=False)),
                ("active", models.BooleanField()),
                ("price", models.CharField(max_length=255)),
                ("picture", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
